name: CMake

# on: [push, pull_request, workflow_dispatch]
on:
    workflow_dispatch:
    push:
        paths-ignore:
            - 'LICENSE.md'
            - 'README.md'
            - '.gitignore'
            - '.gitmodules'
            - '.clang-format'
            - '.prettierrc'
            - '.mxproject'
            - 'openocd.cfg'
            - 'index.md'
            - '.SISPS-PV.ioc'
            - '.vscode/**'
            - 'Altium/**'
            - 'Assets/**'
            - 'docs/**'
            - 'CubeMX/Makefile'
    pull_request:

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                preset: [Debug, Release, Server]

                exclude:
                    - os: windows-latest
                      preset: Server # Always fails. Suspected compiler issue. Marked as exclude for now and repo issue opened.

            fail-fast: false

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: true

            - name: Install ARM Embedded Toolchain
              if: matrix.preset != 'Server'
              uses: carlosperate/arm-none-eabi-gcc-action@v1

            - run: arm-none-eabi-gcc --version
              if: ${{success() && matrix.preset != 'Server'}}

            - name: CMake Configure
              run: |
                  cmake --version
                  cmake --preset ${{matrix.preset}}

            - name: Build
              run: cmake --build --preset ${{matrix.preset}} --parallel $(getconf _NPROCESSORS_ONLN)

            - name: Test
              if: matrix.preset == 'Server'
              run: ctest --preset ${{matrix.preset}} --parallel $(getconf _NPROCESSORS_ONLN)
