name: CMake

on:
    workflow_dispatch:
    push:
        paths-ignore:
            - 'LICENCE.md'
            - 'README.md'
            - '.clang-format'
            - '.editorconfig'
            - '.gitignore'
            - '.gitmodules'
            - '.mxproject'
            - '.prettierrc'
            - 'openocd.cfg'
            - '.SISPS-PV.ioc'
            - '.github/Pages/**'
            - '.github/workflows/pages.yml'
            - '.vscode/**'
            - 'Altium/**'
            - 'Assets/**'
            - 'CubeMX/Makefile'
    pull_request:
        branches: ['main']
    schedule:
        - cron: '0 13 * * 1' # Build deps from Live

jobs:
    build:
        name: Build
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                preset: [Server, Release]
                gcc: ['latest', '12.3.Rel1'] # 11.3 and below has breaking issue with --no-warn-rwx-segment flag.

                exclude:
                    - os: windows-latest
                      preset: Server # Always fails. Suspected compiler issue. Marked as exclude for now and repo issue opened.

            fail-fast: false

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Install ARM Embedded Toolchain
              if: matrix.preset != 'Server'
              uses: carlosperate/arm-none-eabi-gcc-action@v1
              with:
                  release: ${{ matrix.gcc }}

            - run: arm-none-eabi-gcc --version
              if: ${{success() && matrix.preset != 'Server'}}

            - name: CMake Configure
              run: |
                  cmake --version
                  cmake --preset ${{matrix.preset}}

            - name: Build
              run: cmake --build --preset ${{matrix.preset}} --parallel $(getconf _NPROCESSORS_ONLN)

            - name: Test
              if: matrix.preset == 'Server'
              run: ctest --preset ${{matrix.preset}} --parallel $(getconf _NPROCESSORS_ONLN)
