name: CTest

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

env:
    BUILD_TYPE: Release

jobs:
    CTest:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Submodule Update
              run: git submodule update --init --recursive

            - name: Configure CMake
              run: |
                  cmake --version
                  cmake --preset Server

            - name: Build
              run: cmake --build --preset Server --parallel $(getconf _NPROCESSORS_ONLN)

            - name: Test
              run: ctest --preset Server --parallel $(getconf _NPROCESSORS_ONLN)
